// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsonyydsezlsqfwwysye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzb255eWRzZXpsc3Fmd3d5c3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTMwNjIsImV4cCI6MjA2MzQ2OTA2Mn0.x8jHQrzpiEUAduUJeSPzdPRC4_tu2gaR3ZmsjcsYL5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);